# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20160521_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='_question_likes_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
